// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/walk": {
            "post": {
                "description": "Add containers to account",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Walk all urls and get data for every url",
                "parameters": [
                    {
                        "description": "info",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "migrations": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "migrations": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/crawler.Response"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "migrations": {
                            "$ref": "#/definitions/crawler.BaseResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "crawler.BaseResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                },
                "status": {
                    "type": "boolean"
                }
            }
        },
        "crawler.Element": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer"
                },
                "tag-name": {
                    "type": "string"
                }
            }
        },
        "crawler.Meta": {
            "type": "object",
            "properties": {
                "content-length": {
                    "type": "integer"
                },
                "content-type": {
                    "type": "string"
                },
                "status": {
                    "type": "integer"
                }
            }
        },
        "crawler.Response": {
            "type": "object",
            "properties": {
                "elements": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/crawler.Element"
                    }
                },
                "meta": {
                    "$ref": "#/definitions/crawler.Meta"
                },
                "url": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Do API",
	Description:      "API server for application",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
